import{a as p,S as P,i}from"./assets/vendor-BkC4bTqC.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&c(s)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function c(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();p.defaults.baseURL="https://pixabay.com/api/";const $="54694633-cd733223458a0ec40216cbff4";async function g(n,o){return(await p.get("",{params:{key:$,q:n,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}})).data}const m=document.querySelector(".gallery"),C=new P(".gallery a",{captionsData:"alt",captionDelay:250}),h=document.querySelector(".loader"),y=document.querySelector(".load-btn");function L(n){const o=n.map(({webformatURL:r,largeImageURL:c,tags:e,likes:t,views:s,comments:q,downloads:M})=>`
  <li class="gallery-item">
    <a class="gallery-link" href="${c}">
      <img class="gallery-image" src="${r}" alt="${e}" />
    </a>
    <div class="info">
      <p class ="info-item"><span>Likes:</span> ${t}</p>
      <p class ="info-item"><span>Views:</span> ${s}</p>
      <p class ="info-item"><span>Comments:</span> ${q}</p>
      <p class ="info-item"><span>Downloads:</span> ${M}</p>
    </div>
  </li>
`).join("");m.insertAdjacentHTML("beforeend",o),C.refresh()}function R(){m.innerHTML=""}function b(){h.classList.remove("hidden")}function w(){h.classList.add("hidden")}function u(){y.classList.remove("hidden")}function d(){y.classList.add("hidden")}const B=document.querySelector(".form"),f=document.querySelector(".form-input"),O=document.querySelector(".load-btn");B.addEventListener("submit",H);O.addEventListener("click",k);let a=0;const S=15;let v="",l=0;async function H(n){n.preventDefault();const o=f.value.trim();if(v=o,a=1,o===""){i.error({message:"Please enter a search term",backgroundColor:"#ef4040",position:"topRight"});return}R(),d(),b();try{const r=await g(o,a);if(r.hits.length===0){i.error({message:"❌ Sorry, there are no images matching your search query. Please try again!",backgroundColor:"#ef4040",position:"topRight"});return}l=Math.ceil(r.totalHits/S),L(r.hits),a<l&&u()}catch{i.error({message:"Something went wrong. Please try again!",backgroundColor:"#ef4040",position:"topRight",icon:null})}finally{w(),f.value=""}}async function k(){a++,b(),d();try{const n=await g(v,a);L(n.hits),l=Math.ceil(n.totalHits/S),a>=l?(d(),i.info({message:"We're sorry, but you've reached the end of search results!",backgroundColor:"rgba(4, 158, 255, 0.5)",position:"topRight"})):u();const r=document.querySelector(".gallery-item").getBoundingClientRect().height;r&&window.scrollBy({left:0,top:r*2,behavior:"smooth"})}catch{i.error({message:"Something went wrong. Please try again!",backgroundColor:"#ef4040",position:"topRight",icon:null}),u()}finally{w()}}
//# sourceMappingURL=index.js.map
