import{a as f,S as M,i}from"./assets/vendor-BkC4bTqC.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&c(s)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function c(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();f.defaults.baseURL="https://pixabay.com/api/";const P="54694633-cd733223458a0ec40216cbff4";async function p(n,o){return(await f.get("",{params:{key:P,q:n,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}})).data}const g=document.querySelector(".gallery"),$=new M(".gallery a",{captionsData:"alt",captionDelay:250}),m=document.querySelector(".loader"),h=document.querySelector(".load-btn");function y(n){const o=n.map(({webformatURL:r,largeImageURL:c,tags:e,likes:t,views:s,comments:v,downloads:q})=>`
  <li class="gallery-item">
    <a class="gallery-link" href="${c}">
      <img class="gallery-image" src="${r}" alt="${e}" />
    </a>
    <div class="info">
      <p class ="info-item"><span>Likes:</span> ${t}</p>
      <p class ="info-item"><span>Views:</span> ${s}</p>
      <p class ="info-item"><span>Comments:</span> ${v}</p>
      <p class ="info-item"><span>Downloads:</span> ${q}</p>
    </div>
  </li>
`).join("");g.insertAdjacentHTML("beforeend",o),$.refresh()}function C(){g.innerHTML=""}function L(){m.classList.remove("hidden")}function b(){m.classList.add("hidden")}function d(){h.classList.remove("hidden")}function R(){h.classList.add("hidden")}const B=document.querySelector(".form"),u=document.querySelector(".form-input"),O=document.querySelector(".load-btn");B.addEventListener("submit",H);O.addEventListener("click",k);let a=0;const w=15;let S="",l=0;async function H(n){n.preventDefault();const o=u.value.trim();if(S=o,a=1,o===""){i.error({message:"Please enter a search term",backgroundColor:"#ef4040",position:"topRight"});return}C(),L();try{const r=await p(o,a);r.hits.length===0&&i.error({message:"❌ Sorry, there are no images matching your search query. Please try again!",backgroundColor:"#ef4040",position:"topRight"}),l=Math.ceil(r.totalHits/w),y(r.hits),a<l&&d()}catch{i.error({message:"Something went wrong. Please try again!",backgroundColor:"#ef4040",position:"topRight",icon:null})}finally{b(),u.value=""}}async function k(){a++,L(),R();try{const n=await p(S,a);y(n.hits),l=Math.ceil(n.totalHits/w),a>=l?i.info({message:"We're sorry, but you've reached the end of search results!",backgroundColor:"rgba(4, 158, 255, 0.5)",position:"topRight"}):d();const r=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({left:0,top:r*3,behavior:"smooth"})}catch{i.error({message:"Something went wrong. Please try again!",backgroundColor:"#ef4040",position:"topRight",icon:null}),d()}finally{b()}}
//# sourceMappingURL=index.js.map
